### ISSUE TITLE
[Enhancement] Ability to disable CallExpression type

### ISSUE THREAD

**Issue by dmytrous** [donmccurdy/expression-eval#39]
It would be nice if we can disable execution of CallExpression type for better security reason, in case we can't absolutely control data object functions. Function creates through Func() for example.

**Comment by donmccurdy** [comment]
One way of doing this would be to parse first, traverse the AST checking for CallExpression, and then throw an error if something was used that you want to avoid, otherwise go ahead and evaluate. I think that might be easy enough to implement in your application without changes here, but let me know if you run into trouble!

**Comment by dmytrous** [comment]
Yes, but in difficult use cases such as nested conditions '(a && b()) || (c === d) && (e() === f)', it's harder to traverse AST whole object, much easier have a some argument for parse function.

**Comment by donmccurdy** [comment]
The parse function is actually not defined in this repository – it just re-exports https://www.npmjs.com/package/jsep, so I can't modify that myself. This repository defines logic for evaluating the AST that jsep provides, and so if given a CallExpression it does evaluate it...

**Comment by dmytrous** [comment]
I meant 'evaluate' function...

**Comment by donmccurdy** [comment]
Ok, would you want to open a PR? I think an 'options' object could be passed to the evaluate function, like:

```js
evaluate(ast, context, {disable: ['CallExpression']});
```
